---
- hosts: "{{ host_pattern }}"
#  gather_facts: false
 
  tasks:
#  - setup:
#      gather_subset: network

  - name: Get Host DB
    set_fact:
     host_db : "{{ groups['database'] | intersect (groups[host_pattern]) }}"

  - name: Get Host App
    set_fact:
     host_app : "{{ groups['app'] | intersect (groups[host_pattern]) }}"

  - name: Get Host Front
    set_fact:
     host_front : "{{ groups['front'] | intersect (groups[host_pattern]) }}"
  
  - debug:
      msg: |
        IP Host DB: {{ hostvars[host_db]['ansible_facts']['ansible_default_ipv4']['address'] }}
        Host App: {{ hostvars[host_app]['ansible_facts']['ansible_default_ipv4']['address'] }}
        Host Front: {{ hostvars[host_front]['ansible_facts']['ansible_default_ipv4']['address'] }}
    run_once: true
